version: '3.8'

services:

  server:
    build:
      context: /server
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  client:
    build:
      context: /client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server